#' Plot SRM
#'
#' @rdname plotSRM
#' @param object a SRM object
#' @param index a numeric value of the transition index to plot
#' @param type a character string of either `overlay` or `facet`
#' @return a ggplot plot object
#'
#' @export

setGeneric(
  name = 'plotSRM',
  def = function(object, index, type)
  {
    standardGeneric('plotSRM')
  }
)

#' Plot Transform
#'
#' @rdname plotTransform
#' @param object a SRM object
#' @param index a numeric value of the transition index to plot
#' @param sampleID a character string of a valid `sampleName`
#' @return a ggplot plot object
#'
#' @export

setGeneric(
  name = 'plotTransform',
  def = function(object, index, sampleID)
  {
    standardGeneric('plotTransform')
  }
)


#' Plot Parent
#'
#' @rdname plotParent
#' @param object a SRM object
#' @param parentMass a numeric value of the parent mass (Q1) to extract
#' @return a ggplot plot object
#'
#' @export

setGeneric(
  name = 'plotParent',
  def = function(object, parentMass)
  {
    standardGeneric('plotParent')
  }
)


#' Plot Sample
#'
#' @rdname plotSample
#' @param object a SRM object
#' @param sampleName a character string of a valid `sampleName`
#' @param polarity a character string of either `pos` or `neg` for positive and negative ionisation mode respectively
#' @return a ggplot plot object
#'
#' @export


setGeneric(
  name = 'plotSample',
  def = function(object, sampleName, polarity)
  {
    standardGeneric('plotSample')
  }
)

#' Transform Chromatograms
#'
#' @rdname chromTransform
#' @param object a SRM object
#' @param cf matrix, a coefficient matrix generated by MsCoreUtils::coefMA or MsCoreUtils::coefWMA
#' @return a SRM object
#'
#' @export

setGeneric(
  name = 'chromTransform',
  def = function(object, cf)
  {
    standardGeneric('chromTransform')
  }
)


#' Detect Peaks
#'
#' @rdname detectPeaks
#' @param object a SRM object
#'
#' @return a SRM object
#'
#' @export

setGeneric(
  name = 'detectPeaks',
  def = function(object, raw = TRUE, snthresh, fwhm)
  {
    standardGeneric('detectPeaks')
  }
)

#' Plot Peak Area
#'
#' @rdname plotPeakArea
#' @param object a SRM object
#' @param index a numeric value of the transition index to plot
#' @param sampleName a character string of `sampleName` to plot
#' @param type a character string of either `raw` or `transformed`, indicating which chromatography data to use when plotting
#' @return a ggplot plot object
#'
#' @export

setGeneric(
  name = 'plotPeakArea',
  def = function(object, index, sampleName, type)
  {
    standardGeneric('plotPeakArea')
  }
)



#' Filter Peaks
#'
#' @rdname filterPeaks
#' @param object a SRM object
#' @return a `SRM` object
#'
#' @export

setGeneric(
  name = 'filterPeaks',
  def = function(object)
  {
    standardGeneric('filterPeaks')
  }
)

#' Peak Asymmetry
#'
#' @rdname peakAsymmetry
#' @param object a SRM object
#' @return a `SRM` object
#'
#' @export

setGeneric(
  name = 'peakAsymmetry',
  def = function(object)
  {
    standardGeneric('peakAsymmetry')
  }
)



